### ISSUE TITLE
Pixy2 Documentation

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#12]

**Comment by cdmarshall25** [comment]
Some documentation on the Pixy2 setup

https://docs.pixycam.com/wiki/doku.php?id=wiki:v2:porting_guide

**Comment by cdmarshall25** [comment]
From Chief Delphi :

"if you truly want to keep using Java and not use an Arduino or Raspberry PI, I suggest you use this API because it is truly working well for our team so far. Refer to this prior post I made. This provides the API instructions with Gradle/Maven from PseudoResonance’s GitHub Pixy2JavaAPI and the branch from which our team is currently testing the Pixy2 with this API. It is so far promising and you may find it a better method in order to code easier with integration directly to the RoboRIO without the need of a co-processor."

"I recommend you use this (link) and follow the instructions to use the API in the README. I am using the SPI (Pixy2) to SPI (RoboRIO) method but this requires you to wire connections from pin to pin since the pin layout is not the same for each interface."

Link to the code he is talking about : 

https://github.com/PseudoResonance/Pixy2JavaAPI

**Comment by cdmarshall25** [comment]
Haven't watched the entire video yet, but it seems like this dude does a really good job at breaking down what the Pixy2 is capable of, might be a good resource for us to understand this camera and how to make it work better. 

https://www.youtube.com/watch?v=391dXDjqzXA

**Comment by JediScoy** [comment]
Moved to [Cyber Coyotes - Handbook wiki](https://github.com/CyberCoyotes/Handbook/wiki/).
