### ISSUE TITLE
Create auton driving proof concept

### ISSUE THREAD

**Issue by JediScoy** [CyberCoyotes/2022-RapidReact#27]
**Describe the solution you'd like**
Each programmer including mentors creates a simple auton driving task and we will run these together to (1) test our ability to run auton (2) test our ability to schedule multiple auton commands

e.g. I made a branch called "auton-scoy" and a command file "auton_scoy"

**Comment by JediScoy** [comment]
Chief Delphi profile [SeanSun6814](https://www.chiefdelphi.com/u/seansun6814/activity/portfolio)

**Comment by JediScoy** [comment]
[A Video Walkthrough of Model Based Validation of Autonomous in FRC](https://docs.wpilib.org/en/latest/docs/software/advanced-controls/video-walkthrough.html)
I'm only a few minutes into it and not sure if it'll help me code the stuff, lol, but it is helping me with some of the verbage out there; e.g. pose, odometry. Supposedly the gist of the video is its going to show programmer's how to program the robots and test out logic in virtual/sim so you could do it before the robot is built. I'm not sure if that's possible with swerve however,

**Comment by JediScoy** [comment]
I'll leave my video references here but I also turned issue #8 "Autonomous Documentation" so we can use that as a reference. Maybe later in the season we combine our references and resources into one "ReadMe" like doc

**Comment by cdmarshall25** [comment]
I have planted my flag in the auton-Waffle branch

**Comment by cdmarshall25** [comment]
@Fruggg @SignThatSaysTruck @coyotepod 

Scoy and I played around with PathPlanner today instead of PathWeaver. Confusing I know. PathPlanner is supposed to play nicer with the Swerve drive system though.

Scoy made a simple square auton pathway in PathPlanner, and added all libraries needed for this on the _Main branch_ of the code. 

I took his path from PathPlanner, and combined that with the example auton code we were following from SeanSun's YouTube video on my _auton-Waffle branch_, replacing SeanSun's code with the path from PathPlanner as needed. 

As of right now, I have no errors in my code. This may have broken our button inputs again, as with the last time we tried SeanSun's code, but we have to see what happens when we test it out on Monday.
